package GUIProgram;


import Controller.LecturerController;
import Entity.Subject;
import Entity.Lecturer;
import Entity.modules;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class LecturerSignUp extends javax.swing.JFrame {

    private int id;
    private String lecName;
    private int lecAge;
    private String userName;
    private String passowrd;
    private Lecturer lecturer=new Lecturer();
    private ArrayList<Subject> subjectList=new ArrayList<>();
    private LecturerController lecController=new LecturerController();
    public static LecturerSignUp lecSignUp=new LecturerSignUp();
    private LoginPage homePage=new LoginPage();
        
    /**
     * Creates new form MainWindow
     */
    ArrayList<Subject> sbList=new ArrayList<>();
    public LecturerSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label1 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        UserNametxt = new javax.swing.JTextField();
        Passwordtxt = new javax.swing.JTextField();
        RePasswordtxt = new javax.swing.JTextField();
        Label6 = new javax.swing.JLabel();
        Nametxt = new javax.swing.JTextField();
        Agetxt = new javax.swing.JTextField();
        Label2 = new javax.swing.JLabel();
        UserIdtxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Cancelbtn = new javax.swing.JButton();
        SignUpbtn = new javax.swing.JButton();
        checkBox3 = new javax.swing.JCheckBox();
        checkBox2 = new javax.swing.JCheckBox();
        checkBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Label1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Label1.setForeground(new java.awt.Color(51, 0, 153));
        Label1.setText("SIGN UP AS A LECTURER");
        getContentPane().add(Label1);
        Label1.setBounds(64, 60, 265, 29);

        Label3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Label3.setText("User Name");
        getContentPane().add(Label3);
        Label3.setBounds(67, 152, 90, 22);

        Label4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Label4.setText("Password");
        getContentPane().add(Label4);
        Label4.setBounds(67, 194, 80, 22);

        Label5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Label5.setText("Re Type Password");
        getContentPane().add(Label5);
        Label5.setBounds(67, 236, 153, 22);
        getContentPane().add(UserNametxt);
        UserNametxt.setBounds(355, 156, 308, 20);
        getContentPane().add(Passwordtxt);
        Passwordtxt.setBounds(355, 198, 308, 20);
        getContentPane().add(RePasswordtxt);
        RePasswordtxt.setBounds(355, 240, 308, 20);

        Label6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Label6.setText("Full Name");
        getContentPane().add(Label6);
        Label6.setBounds(67, 278, 130, 26);
        getContentPane().add(Nametxt);
        Nametxt.setBounds(355, 284, 308, 20);
        getContentPane().add(Agetxt);
        Agetxt.setBounds(355, 326, 308, 20);

        Label2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Label2.setText("User Id");
        getContentPane().add(Label2);
        Label2.setBounds(67, 117, 59, 22);
        getContentPane().add(UserIdtxt);
        UserIdtxt.setBounds(355, 121, 308, 20);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Cancelbtn.setBackground(new java.awt.Color(0, 0, 153));
        Cancelbtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Cancelbtn.setForeground(new java.awt.Color(153, 255, 255));
        Cancelbtn.setText("Cancel");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });

        SignUpbtn.setBackground(new java.awt.Color(0, 0, 153));
        SignUpbtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        SignUpbtn.setForeground(new java.awt.Color(153, 255, 255));
        SignUpbtn.setText("Sign Up");
        SignUpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpbtnActionPerformed(evt);
            }
        });

        checkBox3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        checkBox3.setText("SENG1113_Data_Structures_and_Algorithms");

        checkBox2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        checkBox2.setText("SENG1112_Fndamantales_of_Engineering");

        checkBox1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        checkBox1.setText("SENG1111_Introduction_to_Programming");

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Subject");

        Label7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Label7.setText("Age");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label7)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SignUpbtn))
                        .addGap(74, 74, 74)
                        .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(Label7)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(checkBox1)
                .addGap(18, 18, 18)
                .addComponent(checkBox2)
                .addGap(18, 18, 18)
                .addComponent(checkBox3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelbtn)
                    .addComponent(SignUpbtn))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpbtnActionPerformed
        try {
            // TODO add your handling code here:
            JFrame frame=new JFrame();
            id=Integer.parseInt(UserIdtxt.getText());
            userName=UserNametxt.getText();
            lecName=Nametxt.getText();
            lecAge=Integer.parseInt(Agetxt.getText());
            passowrd=Passwordtxt.getText();
            lecturer=lecController.lecSignIn(userName, passowrd);
            if(lecturer!=null){
                JOptionPane.showMessageDialog(frame, "Username or password Already Taken by another user..");
            }else{
                if(checkBox1.isSelected()){
                    Subject subject1=new Subject(1,String.valueOf(modules.SENG1111_Introduction_to_Programming));
                    subjectList.add(subject1);
                }
                if(checkBox2.isSelected()){
                    Subject subject2=new Subject(2,String.valueOf(modules.SENG1112_Fndamantales_of_Engineering));
                    subjectList.add(subject2);
                }
                if(checkBox3.isSelected()){
                    Subject subject3=new Subject(3,String.valueOf(modules.SENG1113_Data_Structures_and_Algorithms));
                    subjectList.add(subject3);
                }
                lecController.lecSignUp(id, lecName, lecAge, userName, passowrd, subjectList);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LecturerSignUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LecturerSignUp.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_SignUpbtnActionPerformed

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        // TODO add your handling code here:
        homePage.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_CancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                lecSignUp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Agetxt;
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JTextField Passwordtxt;
    private javax.swing.JTextField RePasswordtxt;
    private javax.swing.JButton SignUpbtn;
    private javax.swing.JTextField UserIdtxt;
    private javax.swing.JTextField UserNametxt;
    private javax.swing.JCheckBox checkBox1;
    private javax.swing.JCheckBox checkBox2;
    private javax.swing.JCheckBox checkBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
