package GUIProgram;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class LoginPage extends javax.swing.JFrame {

    public static StudentSignIn STUDENTSignIn=new StudentSignIn();
    public static StudentSignUp STUDENTSignUp=new StudentSignUp();
    public static LecturerSignUp LECTURERSignUp=new LecturerSignUp();
    public static LecturerSignIn LECTURERSignIn=new LecturerSignIn();
    
    /**
     * Creates new form HomePage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStudentSignUp = new javax.swing.JButton();
        btnLecturerSignUp = new javax.swing.JButton();
        btnStudentSignIn = new javax.swing.JButton();
        btnLecturerSignIn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME TO UNIVERSITY MANAGEMENT SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 46, 568, 33);

        btnStudentSignUp.setBackground(new java.awt.Color(0, 0, 153));
        btnStudentSignUp.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnStudentSignUp.setForeground(new java.awt.Color(153, 255, 255));
        btnStudentSignUp.setText("Sign Up As Student");
        btnStudentSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnStudentSignUp);
        btnStudentSignUp.setBounds(359, 107, 195, 31);

        btnLecturerSignUp.setBackground(new java.awt.Color(0, 0, 153));
        btnLecturerSignUp.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnLecturerSignUp.setForeground(new java.awt.Color(153, 255, 255));
        btnLecturerSignUp.setText("Sign Up As Lecturer");
        btnLecturerSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnLecturerSignUp);
        btnLecturerSignUp.setBounds(359, 156, 195, 31);

        btnStudentSignIn.setBackground(new java.awt.Color(0, 0, 153));
        btnStudentSignIn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnStudentSignIn.setForeground(new java.awt.Color(153, 255, 255));
        btnStudentSignIn.setText("Sign In As Student");
        btnStudentSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentSignInActionPerformed(evt);
            }
        });
        getContentPane().add(btnStudentSignIn);
        btnStudentSignIn.setBounds(359, 217, 195, 31);

        btnLecturerSignIn.setBackground(new java.awt.Color(0, 0, 153));
        btnLecturerSignIn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnLecturerSignIn.setForeground(new java.awt.Color(153, 255, 255));
        btnLecturerSignIn.setText("Sign In As Lecturer");
        btnLecturerSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerSignInActionPerformed(evt);
            }
        });
        getContentPane().add(btnLecturerSignIn);
        btnLecturerSignIn.setBounds(359, 266, 195, 31);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\oop_\\download.png")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentSignUpActionPerformed
        // TODO add your handling code here:
        
        STUDENTSignUp.setVisible(true);
        this.setVisible(false);
        this.dispose();
            
               
      
    }//GEN-LAST:event_btnStudentSignUpActionPerformed

    private void btnLecturerSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerSignUpActionPerformed
        // TODO add your handling code here:
        
        LECTURERSignUp.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
        
              
               
    }//GEN-LAST:event_btnLecturerSignUpActionPerformed

    private void btnStudentSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentSignInActionPerformed
        // TODO add your handling code here:
       
        STUDENTSignIn.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_btnStudentSignInActionPerformed

    private void btnLecturerSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerSignInActionPerformed
        // TODO add your handling code here:
        
        LECTURERSignIn.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_btnLecturerSignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new LoginPage().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLecturerSignIn;
    private javax.swing.JButton btnLecturerSignUp;
    private javax.swing.JButton btnStudentSignIn;
    private javax.swing.JButton btnStudentSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
