package GUIProgram;


import Controller.StudentController;
import Entity.Student;
import Entity.Subject;
import Entity.modules;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class StudentSignUp extends javax.swing.JFrame {

    private int id;
    private String stdName;
    private int stdAge;
    private String userName;
    private String passowrd;
    private Student student=new Student();
    private ArrayList<Subject> subjectList=new ArrayList<>();
    private StudentController stdController=new StudentController();
    public static StudentSignUp stdSignUp=new StudentSignUp();
    private LoginPage loginPage=new LoginPage();
            
           
    /**
     * Creates new form MainWindow
     */
    public StudentSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UserNametxt = new javax.swing.JTextField();
        Passwordtxt = new javax.swing.JTextField();
        RePasswordtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Nametxt = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        UserIdtxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnSignUp = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        checkSub3 = new javax.swing.JCheckBox();
        checkSub2 = new javax.swing.JCheckBox();
        checksub1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("SIGN UP AS A STUDENT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(64, 60, 280, 29);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setText("User Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(67, 153, 90, 22);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(67, 195, 80, 22);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setText("Re Type Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(67, 237, 153, 22);
        getContentPane().add(UserNametxt);
        UserNametxt.setBounds(355, 157, 308, 20);
        getContentPane().add(Passwordtxt);
        Passwordtxt.setBounds(355, 199, 308, 20);
        getContentPane().add(RePasswordtxt);
        RePasswordtxt.setBounds(355, 241, 308, 20);

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setText("Full Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(67, 279, 130, 26);
        getContentPane().add(Nametxt);
        Nametxt.setBounds(355, 285, 308, 20);
        getContentPane().add(txtAge);
        txtAge.setBounds(355, 327, 308, 20);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("User Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(67, 118, 59, 22);
        getContentPane().add(UserIdtxt);
        UserIdtxt.setBounds(355, 122, 308, 20);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        btnSignUp.setBackground(new java.awt.Color(0, 0, 153));
        btnSignUp.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(153, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 0, 153));
        btnCancel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(153, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        checkSub3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        checkSub3.setText("SENG1113_Data_Structures_and_Algorithms");

        checkSub2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        checkSub2.setText("SENG1112_Fndamantales_of_Engineering");

        checksub1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        checksub1.setText("SENG1111_Introduction_to_Programming");

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Subject");

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setText("Age");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checksub1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkSub3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(checksub1)
                .addGap(18, 18, 18)
                .addComponent(checkSub2)
                .addGap(18, 18, 18)
                .addComponent(checkSub3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignUp)
                    .addComponent(btnCancel))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        try {
            // TODO add your handling code here:
            JFrame frame=new JFrame();
            id=Integer.parseInt(UserIdtxt.getText());
            userName=UserNametxt.getText();
            stdName=Nametxt.getText();
            stdAge=Integer.parseInt(txtAge.getText());
            passowrd=Passwordtxt.getText();
            student=stdController.stdSignIn(userName, passowrd);
            if(student!=null){
                JOptionPane.showMessageDialog(frame, "UserName and Password Already Taken Try another user..");
            
            }else{
                if(checksub1.isSelected()){
                Subject subject1=new Subject(1,String.valueOf(modules.SENG1111_Introduction_to_Programming));
                subjectList.add(subject1);
            }
            if(checkSub2.isSelected()){
                Subject subject2=new Subject(2,String.valueOf(modules.SENG1112_Fndamantales_of_Engineering));
                subjectList.add(subject2);
            }
            if(checkSub3.isSelected()){
                Subject subject3=new Subject(3,String.valueOf(modules.SENG1113_Data_Structures_and_Algorithms));
                subjectList.add(subject3);
            }
            stdController.stdSignUp(id, stdName, stdAge, userName, passowrd, subjectList);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentSignUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StudentSignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
       loginPage.setVisible(true);
       this.setVisible(false);
       this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                stdSignUp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nametxt;
    private javax.swing.JTextField Passwordtxt;
    private javax.swing.JTextField RePasswordtxt;
    private javax.swing.JTextField UserIdtxt;
    private javax.swing.JTextField UserNametxt;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JCheckBox checkSub2;
    private javax.swing.JCheckBox checkSub3;
    private javax.swing.JCheckBox checksub1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAge;
    // End of variables declaration//GEN-END:variables
}
